### ISSUE TITLE
Chore: add CI and release workflow configuration

### ISSUE THREAD

**Issue by glassk** [YOCOING/YOCO#34]
## Summary

> Summarize your issue

Add CI Workflow Configuration(Merges from dev to main)

## To-Do

- [x] test(vscode, mocha)
- [x] push git tag 
- [x] update release note or change log

## ETC

> Etc
